### ISSUE TITLE
How to get paticipaint in channel/group? 

### ISSUE THREAD

**Issue by tiulinh** [celestix/gotgproto#25]
How to get paticipaint in channel/group?  please help me!

**Comment by TeaDove** [comment]
Something like this:
```go
switch t := update.EffectiveChat().(type) {
	case *types.Chat:
		chat := r.telegramManager.Chat(t.Raw())
		chatMembers := members.Chat(chat)
		err := chatMembers.ForEach(ctx, compileMention)
		if err != nil {
			return err
		}
	case *types.Channel:
		chat := r.telegramManager.Channel(t.Raw())
		chatMembers := members.Channel(chat)
		err := chatMembers.ForEach(ctx, compileMention)
		if err != nil {
			return err
		}
	default:
		_, err := ctx.Reply(update, "Err: this command work only in chats", nil)
		return err
	}
```

You can find whole example here: https://github.com/TeaDove/fun-telegram/blob/feature/persistent-storage/internal/presentation/telegram/pingCommand.go#L14

**Comment by tiulinh** [comment]
Thank you so much!

**Comment by tiulinh** [comment]
> Something like this:
> 
> ```go
> switch t := update.EffectiveChat().(type) {
> 	case *types.Chat:
> 		chat := r.telegramManager.Chat(t.Raw())
> 		chatMembers := members.Chat(chat)
> 		err := chatMembers.ForEach(ctx, compileMention)
> 		if err != nil {
> 			return err
> 		}
> 	case *types.Channel:
> 		chat := r.telegramManager.Channel(t.Raw())
> 		chatMembers := members.Channel(chat)
> 		err := chatMembers.ForEach(ctx, compileMention)
> 		if err != nil {
> 			return err
> 		}
> 	default:
> 		_, err := ctx.Reply(update, "Err: this command work only in chats", nil)
> 		return err
> 	}
> ```
> 
> You can find whole example here: https://github.com/TeaDove/fun-telegram/blob/feature/persistent-storage/internal/presentation/telegram/pingCommand.go#L14

are there any way get get paticipaint in channel/group with input: Username/ ID channel/group?
