### ISSUE TITLE
Using html.String returns null message text and raises MESSAGE_EMPTY

### ISSUE THREAD

**Issue by TeaDove** [celestix/gotgproto#26]
**Describe the bug**
When using html.String with ctx.Reply, html text is not parsed, but message sends and TG return MESSAGE_EMPTY error:
```go
_, err := ctx.Reply(
		update,
		[]styling.StyledTextOption{html.String(nil, "<code>Hi!</code>")},
		nil,
	)
```
returns err: `send styled text: rpcDoRequest: rpc error code 400: MESSAGE_EMPTY`  

Almost the same code, using pure gotg works just fine.

**To Reproduce**
1. create reply using `ctx.Reply`
2. `[]styling.StyledTextOption{html.String(nil, htmlMessage)}`, where `htmlMessage` - any text with html
3. send reply

**Expected behavior**
Sends HTML parsed message

**Environment**
MAC OS, M1, github.com/anonyindian/gotgproto v1.0.0-beta10, User bots.

**Comment by celestix** [comment]
> **Describe the bug** When using html.String with ctx.Reply, html text is not parsed, but message sends and TG return MESSAGE_EMPTY error:
> 
> ```go
> _, err := ctx.Reply(
> 		update,
> 		[]styling.StyledTextOption{html.String(nil, "<code>Hi!</code>")},
> 		nil,
> 	)
> ```
> 
> returns err: `send styled text: rpcDoRequest: rpc error code 400: MESSAGE_EMPTY`
> 
> Almost the same code, using pure gotg works just fine.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. create reply using `ctx.Reply`
> 2. `[]styling.StyledTextOption{html.String(nil, htmlMessage)}`, where `htmlMessage` - any text with html
> 3. send reply
> 
> **Expected behavior** Sends HTML parsed message
> 
> **Environment** MAC OS, M1, github.com/anonyindian/gotgproto v1.0.0-beta10, User bots.

Hi! The library doesn't support HTML yet, you can use native style helpers or entity helpers which are provided by gotgproto
