### ISSUE TITLE
Your phone number has been banned

### ISSUE THREAD

**Issue by JWo1F** [celestix/gotgproto#27]
Hi everyone, I tried your app on a newly created telegram account and immediately after authorization I got a ban from telegram. I'm not sure if it's a bug, but somehow telegram knows how to distinguish between real login and login through this library.

**Comment by celestix** [comment]
> Hi everyone, I tried your app on a newly created telegram account and immediately after authorization I got a ban from telegram. I'm not sure if it's a bug, but somehow telegram knows how to distinguish between real login and login through this library.

Yes, I think you used telegram's own app id and hash (api id 6 for an example) which make your client a suspect if used on a newly made account.

**Comment by JWo1F** [comment]
Thank you. It's strange, but I don't want to try it on my main profile :)
