### ISSUE TITLE
Error code 400: CHANNEL_INVALID 

### ISSUE THREAD

**Issue by tiulinh** [celestix/gotgproto#28]
i use this to get participants in group but report error 400: CHANNEL_INVALID
```
_, ok := client.API().ChannelsGetParticipants(context.Background(), &tg.ChannelsGetParticipantsRequest{Channel: &tg.InputChannel{ChannelID: -1001933086941}, Filter: &tg.ChannelParticipantsRecent{}})
fmt.Println("Ok: ", ok)
```
Please help me to fix!

**Comment by celestix** [comment]
You need to provide access hash along with channel ID in InputChannel.
You can check for access hash in update entities or in gotgproto's peer storage (read methods in context.go if you don't know how to use the storage module).

**Comment by tiulinh** [comment]
thank you so much!

**Comment by tiulinh** [comment]
> You need to provide access hash along with channel ID in InputChannel. You can check for access hash in update entities or in gotgproto's peer storage (read methods in context.go if you don't know how to use the storage module).

i try many ways but i can not to use gotgproto's peer storage. Can you help me more detail this?

**Comment by celestix** [comment]
```go
cPeer := peerStorage.GetPeerById(-1001933086941)
_, err := client.API().ChannelsGetParticipants(context.Background(), &tg.ChannelsGetParticipantsRequest{Channel: &tg.InputChannel{ChannelID: cPeer.ID, AccessHash: cPeer.AccessHash}, Filter: &tg.ChannelParticipantsRecent{}})
fmt.Println("Error?: ", err)
```

Note that the chat access hash you're trying to resolve has to be saved in the peer storage already.
