### ISSUE TITLE
channels.getAdminedPublicChannels analogy

### ISSUE THREAD

**Issue by jurakontor** [celestix/gotgproto#34]
Dear team,
First of all i wanted to thank you for such great library, awesome job!

I have an question: i need to fetch all channels, even if its private, where i am an admin. For public channels, i m using channels.getAdminedPublicChannels and it works fine. 
for example, web telegram is able to show me all channels, even if it is private and i am an admin there. Any idea how it could be done with hekp of MTProto?

thanks

**Comment by celestix** [comment]
You should check simple "chat" methods for it.
