### ISSUE TITLE
Change gorm default sqlite driver,cancel cgo dependency

### ISSUE THREAD

**Issue by luomoxu** [celestix/gotgproto#39]
If use memery session,Frequent reacquisition of sessions will be restricted by the server
But use Sqlite Session will Compilation failed when cross compiling
Because gorm default sql drivers is github.com/mattn/go-sqlite3,It is cgo package
So can replace it to https://github.com/glebarez/sqlite

**Comment by EverythingSuckz** [comment]
This might really help my issues with cross compiling. Thank you @luomoxu for pointing this out.

**Comment by ALiwoto** [comment]
This sounds nice, we might also replace our other projects with this non-cgo sqlite lib as well. Just first we have to make sure they are really compatible.

**Comment by luomoxu** [comment]
> This sounds nice, we might also replace our other projects with this non-cgo sqlite lib as well. Just first we have to make sure they are really compatible.这听起来不错，我们也可能用这个非 cgo sqlite 库替换我们的其他项目。首先，我们必须确保它们真正兼容。
There shouldn't be any big problems,gorm officially also recommended this package
https://github.com/go-gorm/sqlite

**Comment by celestix** [comment]
Nice one, thanks for letting us know about! We will add it as soon as possible.
