### ISSUE TITLE
Pseudo random number should not be used for RandomIDs

### ISSUE THREAD

**Issue by TrixiS** [celestix/gotgproto#53]
`ext.Context` uses `random.Int63` in its `generateRandomID` method which causes race conditions on parallel request sending.

**Comment by celestix** [comment]
Have you tried the unreleased version that covers up this commit ?
https://github.com/celestix/gotgproto/commit/2c72092f58611732978ab05006743ef4e4e15cb4

**Comment by TrixiS** [comment]
Now it works. Thanks a lot!
