### ISSUE TITLE
When I use: [StringSession ，TelethonSession ] Unable to start main.go

### ISSUE THREAD

**Issue by TNT-ma** [celestix/gotgproto#63]
&gotgproto.ClientOpts{
			Session: sessionMaker.StringSession("test").
				// Sqlite session name (if you're not using memory session)
				// i.e. InMemory in ClientOpts is set to false
				// It will be saved as my_session.session as per this example.
				Name("my_session"),

I want to set the session, but the following error occurs. Using SimpleSession() is normal

```
failed to start client: invalid character 'µ' looking for beginning of value
```

**Comment by celestix** [comment]
You are supposed to input your gotgproto session string as an argument to `sessionMaker.StringSession`, just writing a random string like "test" won't work.
