### ISSUE TITLE
cant start the program because of the internal error in the library

### ISSUE THREAD

**Issue by XT3RM1NATOR** [celestix/gotgproto#69]
<img width="1639" alt="Screenshot 2024-04-27 at 12 36 11" src="https://github.com/celestix/gotgproto/assets/115317256/ea431696-588f-48fe-9402-697181e8467b">

this says it all

**Comment by celestix** [comment]
Hi @XT3RM1NATOR, it seems like the version of gotd you are using conflicting with the version of gotgproto you have installed. Please remove gotd and gotgproto from the go.mod and try to fetch gotgproto again.

**Comment by celestix** [comment]
> Hi @XT3RM1NATOR, it seems like the version of gotd you are using conflicting with the version of gotgproto you have installed. Please remove gotd and gotgproto from the go.mod and try to fetch gotgproto again.

Also, which version of gotgproto you are using?

**Comment by XT3RM1NATOR** [comment]
<img width="446" alt="Screenshot 2024-04-27 at 15 32 50" src="https://github.com/celestix/gotgproto/assets/115317256/62cd1faa-075c-42a7-8dd9-faec5878fd8f">
both are supposed to be the latest ones, so cant understand on why am i getting the error

**Comment by celestix** [comment]
> <img alt="Screenshot 2024-04-27 at 15 32 50" width="446" src="https://private-user-images.githubusercontent.com/115317256/326171992-62cd1faa-075c-42a7-8dd9-faec5878fd8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMjM3NzUsIm5iZiI6MTcxNDIyMzQ3NSwicGF0aCI6Ii8xMTUzMTcyNTYvMzI2MTcxOTkyLTYyY2QxZmFhLTA3NWMtNDJhNy04ZGQ5LWZhZWM1ODc4ZmQ4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QxMzExMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2JiOTY2NjI1NzkxY2FiZTQxZGZlNTA1MTI1MGU0OWJjNWU5ODkxZjJlMzlkNGU4MDExZjIwOTdiMzExNGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.k2KwF2j6amlsxsjPGwOFqg1GjTCkKsjW__RYk7A4Zmw"> both are supposed to be the latest ones, so cant understand on why am i getting the error

No, You're doing it incorrectly. gotgproto internally depends on gotd, and hence you don't have to explicitly include it in your gomod. Also, gotgproto v1.0.0-beta17 needs gotd v0.99.2:

![image](https://github.com/celestix/gotgproto/assets/73958752/a64836e0-7c79-4b18-bd6f-04f588b0876f)

Just don't include gotd explicitly, gomod will resolve the correct version of gotd automatically if you just include gotgproto.
