### ISSUE TITLE
When creating a new client it starts asking the authentication by itself

### ISSUE THREAD

**Issue by XT3RM1NATOR** [celestix/gotgproto#70]
<img width="457" alt="Screenshot 2024-04-27 at 18 29 40" src="https://github.com/celestix/gotgproto/assets/115317256/ff2d78de-2f8f-4d68-8a1f-6a70299a86cc">

I have a problem, when i create a new client it starts handling the authentication itself asking me the code in the terminal, and though it is good, it does it in the terminal is what is bad. 

<img width="666" alt="Screenshot 2024-04-27 at 18 29 12" src="https://github.com/celestix/gotgproto/assets/115317256/f2af2306-66cd-47f7-b012-017b0343444c">

You see in my platform people will be sending the data through rest and then i have to pass it in manually through the functions it canе the handled through terminal. Is there a way to either cancel the option of terminal auth, or switching it to a different approach. Cuz because it tries to manually handle the authentication i cannot use regular client.Auth().SignIn() with it. Thanks in advance

**Comment by celestix** [comment]
You can create your own custom auth conversators which let you enter mobile number, otp, and password using callback functions. 

Checkout this example (It implements an HTTP API conversator):
https://github.com/celestix/gotgproto/tree/beta/examples/auth-using-api-base

**Comment by celestix** [comment]
> If i want to manage the authentication myself is there a way i can just turn off all of the options and just manage it by client.Auth().sendCode... and client.Auth().SignIn?

What options are you referring to?

**Comment by XT3RM1NATOR** [comment]
these options
<img width="384" alt="Screenshot 2024-04-28 at 15 17 28" src="https://github.com/celestix/gotgproto/assets/115317256/6a085cce-e1cc-421a-8f6d-0cb4dbedac33">
so it does not try to handle the authentication by itself and let me do the job

**Comment by XT3RM1NATOR** [comment]
I just want to handle the myself because all of the ways that are offered are not suitable for me

**Comment by celestix** [comment]
It has all the methods to handle it, just look at the API mehods present in the example.
