### ISSUE TITLE
Internal library error

### ISSUE THREAD

**Issue by timohahaa** [celestix/gotgproto#74]
Trying to run a program using this library I get an error (picture below). Is it an error on my side (that is GOCACHE or pkg/mod pkg/sumdb related stuff) or an error on your side?
![Screenshot from 2024-05-05 22-38-02](https://github.com/celestix/gotgproto/assets/120326782/d05a3d21-bd67-4ca1-bb12-79add9133e1f)

**Comment by celestix** [comment]
Do not include gotd explicitly in your go.mod

Refer to https://github.com/celestix/gotgproto/issues/69

**Comment by celestix** [comment]
Should be fixed now.
