### ISSUE TITLE
How to retrieve latest messages using chat id only

### ISSUE THREAD

**Issue by TheKaram** [celestix/gotgproto#76]
Hello, 
thank you for this wonderful library, but I was looking for a way to retrieve the latest messages in a specific chat by its ID only, and I could not figure out how.

**Comment by celestix** [comment]
Hi @TheKaram, if you can use `Context.GetMessages` (ext/context.go) helper method for that.

**Comment by TheKaram** [comment]
Thanks for replying, `Context.GetMessages` needs message ids to retrieve messages, i want something like [this](https://docs.pyrogram.org/api/methods/get_chat_history).

**Comment by celestix** [comment]
> Thanks for replying, `Context.GetMessages` needs message ids to retrieve messages, i want something like [this](https://docs.pyrogram.org/api/methods/get_chat_history).

Have you tried client.API().MessagesGetHistory(...)? I think that's the method you're looking for.

**Comment by celestix** [comment]
Dead conversation.
