### ISSUE TITLE
How to retrieve all the users in pending join requests using chat id only

### ISSUE THREAD

**Issue by annihilatorrrr** [celestix/gotgproto#77]

**Comment by celestix** [comment]
Hello @annihilatorrrr, There is no helper method for that in the library yet but you can use the lower level gotd function for that:

![image](https://github.com/celestix/gotgproto/assets/73958752/9bdaed24-cdff-4d68-87b0-a48f178ac1d4)

**Comment by annihilatorrrr** [comment]
Ic thanks.
