### ISSUE TITLE
auth-using-api-base example doesn't work

### ISSUE THREAD

**Issue by dev-freelance-ru** [celestix/gotgproto#79]
Allways stuck at `Rec [phone|code|...]`. Works fine with `make` of channels:
```go
func GetWebAuth() *webAuth {
	return &webAuth{
		phoneChan:  make(chan string),
		codeChan:   make(chan string),
		passwdChan: make(chan string),
	}
}
```

**Comment by celestix** [comment]
What do you mean? Please elaborate.

**Comment by celestix** [comment]
Hi

> Allways stuck at `Rec [phone|code|...]`. Works fine with `make` of channels:
> 
> ```go
> func GetWebAuth() *webAuth {
> 	return &webAuth{
> 		phoneChan:  make(chan string),
> 		codeChan:   make(chan string),
> 		passwdChan: make(chan string),
> 	}
> }
> ```

Good catch! Please make a PR for this change.

**Comment by dev-freelance-ru** [comment]
Hi! Ok, a little later today.
