### ISSUE TITLE
Possible to login as user without 2FA prompt? 

### ISSUE THREAD

**Issue by m-quigley** [celestix/gotgproto#81]
Hi there

I'm wondering if its possible to init the client as user without the need to provide the 2FA code? My Telegram account does not have 2FA enabled. 

```
tgClient, err := gotgproto.NewClient(
			cfg.AppId,
			cfg.AppHash,
			gotgproto.ClientTypePhone("REDACTED"),
			&gotgproto.ClientOpts{
				Session: sessionMaker.SqlSession(sqlite.Open("echobot")),
			},
		)
```

I'm aware of other libs, tdl in JS for example that do not require the 2FA code, just appId and appHash. 

Thanks!

**Comment by celestix** [comment]
Hey @m-quigley! 2FA is an optional feature of telegram, and hence it is optional in this library as well. If your account doesn't have 2FA then gotgproto won't ask you 2FA password while logging in.

**Comment by m-quigley** [comment]
hey @celestix  - thanks for the quick reply!

I would expect as much, but I'm using my personal account app/hash
<img width="616" alt="Screenshot 2024-06-19 at 1 24 55 am" src="https://github.com/celestix/gotgproto/assets/47997170/a0100adf-7323-4013-bc2c-1130de68a41a">

you can see from this screenshot I dont have 2FA enabled and I still get prompted to retrieve the code from telegram/enter it when authenticating fresh using gotgproto

I assume I'm misunderstanding something here?

**Comment by celestix** [comment]
> hey @celestix  - thanks for the quick reply!
> 
> I would expect as much, but I'm using my personal account app/hash and you can see from this screenshot I dont have 2FA enabled and I still get prompted to retrieve the code from telegram/enter it when authenticating fresh using gotgproto
> <img width="616" alt="Screenshot 2024-06-19 at 1 24 55 am" src="https://github.com/celestix/gotgproto/assets/47997170/a0100adf-7323-4013-bc2c-1130de68a41a">
> 
> 
> I assume I'm misunderstanding something here?

That is not 2FA, it's the standard telegram OTP you would always need to login.

**Comment by m-quigley** [comment]
ah, right gotcha 
would you happen to know the expiry time for a session of this type?

**Comment by celestix** [comment]
> ah, right gotcha would you happen to know the expiry time for a session of this type?

There is no expiry, as long as you have it authenticated, it will stay active.

**Comment by m-quigley** [comment]
legend! thanks for your hard work @celestix
