### ISSUE TITLE
Hope to add examples of sending pictures, sending files, getting chat history, getting carbon dioxide, etc.

### ISSUE THREAD

**Issue by pd5200** [celestix/gotgproto#83]
This can greatly reduce the difficulty of use and increase the number of people using it.

**Comment by celestix** [comment]
Thanks for the suggestion, I'll add a few more examples soon.

**Comment by lucabarletta** [comment]
would love to see how we can get the chat history <3

**Comment by celestix** [comment]
Hi @pd5200 and @lucabarletta, I have created a basic operations section in the readme containing some example usages, have a look at them and let me know if any tweaks are needed :)

https://github.com/celestix/gotgproto#basic-operations

**Comment by lucabarletta** [comment]
Thanks alot!
