### ISSUE TITLE
When monitoring messages, duplicate messages will be obtained？

### ISSUE THREAD

**Issue by crispony** [celestix/gotgproto#98]
The msg.ID obtained is the same，

dispatcher.AddHandler(handlers.NewMessage(filters.Message.Chat(channelId), TEST))

func TEST(ctx *ext.Context, update *ext.Update) error {
	msg := update.EffectiveMessage
	channel := update.GetChannel()
	//user := update.EffectiveUser()
	chat := update.EffectiveChat()
	fmt.Println(reflect.TypeOf(chat))
	log.Println(channel.ID, channel.Title, msg.Text)
	return nil
}

**Comment by celestix** [comment]
Hi @crispony, this filter will be triggered every time when the incoming message has the filtered chat/channel id.

Please elaborate your query if this doesn't clear your doubts.

**Comment by crispony** [comment]
The same message may be triggered twice or three times, and the message ID is the same.

**Comment by crispony** [comment]
func TEST(ctx *ext.Context, update *ext.Update) error {
	msg := update.EffectiveMessage
	channel := update.GetChannel()
	user := update.EffectiveUser()
	chat := update.EffectiveChat()
	log.Println(msg.ID, reflect.TypeOf(chat))
	log.Printf("[%s]%s", channel.Title, user.FirstName)
	return nil
}
![QQ20241026-191001](https://github.com/user-attachments/assets/585ef41c-d424-4ee2-ac6c-0698feb49521)

**Comment by crispony** [comment]
It does not happen every time, it is a probabilistic event

**Comment by asdfzxcvbn** [comment]
why close if it still happens sometimes? im getting the same issue but manually filtering the channel id inside the handler func
